spring.application.name=smart-clinic

# Shared application settings
server.port=8080

# Default profile: MySQL
spring.profiles.active=mysql

# Common logging
logging.level.root=INFO
logging.level.org.springframework=INFO
