spring.application.name=demo

# MYSQL

spring.datasource.url=jdbc:mysql://localhost:3306/hsptl_mngmt?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

# MONGO

spring.data.mongodb.uri=
spring.mongodb.database=smartclinic