# MongoDB configuration
spring.mongodb.uri=mongodb://localhost:27017/smartclinic
spring.mongodb.database=smartclinic
spring.data.mongodb.auto-index-creation=true

# Disable JPA for this profile if you want Mongo only
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
